### ISSUE TITLE
Latest version not installed after a fresh installation

### ISSUE THREAD

**Issue by arunsathiya** [humblepenguinn/envio#15]
I just installed using `cargo install envio` but it seems that I  have 0.4.0 while the latest version is 0.4.1. I am not familiar with Rust tooling, so is it a cargo error that the latest version wasn't installed, or something that needs to be done on envio's side for cargo to install the latest version?

**Comment by humblepenguinn** [comment]
Sorry, that's my bad, I forgot to publish the latest release to the cargo repo. It should be available now
