### ISSUE TITLE
When using subcommand it's unclear how to list out profiles

### ISSUE THREAD

**Issue by ccastleberry** [humblepenguinn/envio#2]
When I try to using the command `envio list` I get an `Error: Invalid number of arguments` exception. 

The command works properly when listing the variables in an existing environment but I cannot figure out how to get is to list the available profiles.

**Comment by humblepenguinn** [comment]
To list the available profiles pass in `profiles` as the argument

So the command would be:
`envio list profiles`

**Comment by afolksetapart** [comment]
@humblepenguinn would you be open to returning usage suggestions for incomplete commands? This is something I'd be willing to take on.

**Comment by humblepenguinn** [comment]
> @humblepenguinn would you be open to returning usage suggestions for incomplete commands? This is something I'd be willing to take on.

Sure, that sounds like a great idea.

Open a issue and submit a PR when your done

Good luck!
