### ISSUE TITLE
Support Fish

### ISSUE THREAD

**Issue by matthias-Q** [humblepenguinn/envio#9]
Hi,
do you have any plans to support the fish shell? When I run envio I get prompted that this shell is not supported and I should source the unencrypted file instead (which makes this program useless)
Would be really great!

**Comment by humblepenguinn** [comment]
Hey,

It's not asking you to source the unencrypted file but to rather source the `shell-script` which envio uses to load and unload your profiles. So all you have to do is add that line to your fish config and the program should work. 

However, we do plan to support fish. 

If you're willing to take on a task, would you be interested in adding support for fish? If so, we'd be happy to review and merge your pull request!

**Comment by humblepenguinn** [comment]
Hey,

support for fish has been added in the latest release (v0.3.0)!

**Comment by Nithe14** [comment]
Hi!
I can confirm that it works very well with the fish shell now. Thank you @humblepenguinn!

**Comment by matthias-Q** [comment]
I have tried to load a ENV, sourced my config.fish again, but I don't see the ENV variable with `env`

**Comment by humblepenguinn** [comment]
Do you have any environment variables in the profile that you loaded? 

Run the command below to see:
`envio list <profile_name>`

**Comment by matthias-Q** [comment]
Yes, I have created a new profile and added one Variable

**Comment by matthias-Q** [comment]
Yes, fish is my default shell and I ran `envio load <profile>`

**Comment by matthias-Q** [comment]
![image](https://user-images.githubusercontent.com/35303817/228873433-d7857d77-95cf-4a59-941b-249216b51fb2.png)

**Comment by humblepenguinn** [comment]
Thats really weird, I tried it again, just like in the screenshot you sent and it works. Does your fish config has the line 
`source /home/yourusername/.envio/setenv.sh`

If it does try closing and re opening your shell session again.

**Comment by matthias-Q** [comment]
In fish `source /home/yourusername/.envio/setenv.sh` will not work. Instead I used `bass source /home/yourusername/.envio/setenv.sh`.
I was missing that part (I that in the user guide?)

Now it works.

**Comment by matthias-Q** [comment]
No problem. That is the main criticism most people have on fish, that it is not posix conform.
